service: api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

# functions
functions:
  hello:
    handler: src/functions/hello.handler
    events: # The events that trigger this function
      - http: 
          path: api/hello
          method: get
          documentation:
          summary: "Create User"
          description: "Creates a user and then sends a generated password email"
  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http: 
          path: api/goodbye
          method: post


# Serverless plugins
plugins:
  - serverless-auto-swagger
  - serverless-plugin-typescript
  - serverless-offline

# Resources your functions use
