// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "api",
    "version": "1"
  },
  "paths": {
    "/api/hello": {
      "get": {
        "summary": "Create User",
        "description": "Creates a user and then sends a generated password email",
        "operationId": "hello.get.api/hello",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/goodbye": {
      "post": {
        "summary": "goodbye",
        "description": "",
        "operationId": "goodbye.post.api/goodbye",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};